;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Avility",NewTagName="Ability")
+GameplayTagRedirects=(OldTagName="GameplayCue.Hit.Skill.Valkyrie.Hammer_1",NewTagName="GameplayCue.Hit.Skill.Valkyrie.Hammer1")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="GameplayCue.Hit.Attack.Normal",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Skill.Valkyrie.Axe1",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Skill.Valkyrie.Bow1",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Skill.Valkyrie.Hammer1",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Skill.Valkyrie.Staff1",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Skill.Valkyrie.Staff2",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Notify.Skill.Valkyrie.Staff_2",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Start.Skill.Valkyrie.Axe1",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Start.Skill.Valkyrie.Staff2",DevComment="")

